def game_hash
   { 
     home: 
      { team_name: "Brooklyn Nets", 
        colors:[""], 
        players: [
          {
            player_name: 
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
          }
          {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
          ]
      }
    away: 
      { team_name: "Charlotte Hornets", 
        colors:[""], 
        players: [
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
            {
            player_name:
            number:
            shoe:
            points:
            rebounds:
            assists:
            steals:
            blocks:
            slam_dunks:
            }
          ]
      }
   }
end
